export enum BrtToolId {
  BUGZILLA = 'BRTTOOLID.BUGZILLA',
  GITHUB = 'BRTTOOLID.GITHUB',
  GITLAB = 'BRTTOOLID.GITLAB',
  JIRA = 'BRTTOOLID.JIRA',
  MANTIS = 'BRTTOOLID.MANTIS',
  TRELLO = 'BRTTOOLID.TRELLO',
  USER = 'BRTTOOLID.USER',
  ZOHOBT = 'BRTTOOLID.ZOHOBT',
}
